- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore:
    ~/.aria2/aria2.conf:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gdbinit:
    ~/.gitconfig:
    ~/.cgdb:
    ~/.gitignore_global:
    ~/.ripgreprc:
    ~/.shell:
    ~/.config/tmux: tmux
    ~/.tmux.conf: tmux/tmux.conf
    ~/.config/lazygit: lazygit
    ~/.config/nvim: nvim
    ~/.vim: vim
    ~/.vimrc: vim/vimrc
    ~/.config/lvim: lvim
    ~/.config/zellij: zellij
    ~/.config/alacritty: alacritty 
    ~/.vimrc_local:
    ~/.ideavimrc:
    ~/.vsvimrc: vscode/vsvimrc
    ~/.oh-my-zsh:
    ~/.zshrc:
    ~/.shell_local_before:
    ~/.config/helix/config.toml: helix/config.toml
    ~/.config/helix/languages.toml: helix/languages.toml
    # ~/.zfunctions/prompt_spaceship_setup: zsh/prompt/spaceship-prompt/spaceship.zsh

- create:
  - ~/.rtorrent/session
  - ~/.rtorrent/watch
  - ~/.rtorrent/downloads

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
  - >
    git cleanall -f
    shell/plugins/
    zsh/plugins/
