""""""""""""""""""""""""""""""""""
"	basic settings
""""""""""""""""""""""""""""""""""

" set leader key
nnoremap <SPACE> <Nop>
let mapleader=" "

filetype plugin on
syntax on
set number
set incsearch " incremental search (as string is being typed)
set hls " highlight search
set mouse+=a " enable mouse mode (scrolling, selection, etc)
set cursorline " hight current line"
set clipboard+=unnamed " copy to clipboard"


" p will not overwrite register
xnoremap p "_dP

" window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Moving text
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

" quit & save
nmap <Leader>q :q<CR>
nmap <Leader>w :w<CR>

" line head & tail
map H ^
map L $

" cancel highlight
nnoremap <silent> <Leader>h :<C-u>nohlsearch<CR><C-l>

" buffer loop
nmap R :bnext<CR>
nmap E :bprev<CR>
