# plugins install start
# type prefix + I to fetch plugins
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'         # Copy to the system clipboard in tmux.  https://github.com/tmux-plugins/tmux-yank
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-open'         # open highlighted text 
set -g @plugin 'ravenxrz/tmux-plugin-sysstat'         # sysstat
# set -g @plugin 'schasje/tmux-jump'              # vim easymotion like plugin. https://github.com/schasse/tmux-jump
# set -g @plugin 'Morantron/tmux-fingers'         # press prefix +F to enter finger mode, and press <Tab> to enter multi-selection mode
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.config/tmux/tpm/tpm'
# plugins install end

# Keep status stats, but refresh less often than the original 2s interval.
set -g status-interval 10
set -g status-right '#[fg=colour76]#{sysstat_cpu} #{sysstat_mem} - #[fg=colour33]%d %b %Y #{?client_prefix,#[fg=colour160],#[fg=colour61]}- #[fg=colour64]%I:%M %p #{?client_prefix,#[fg=colour160],#[fg=colour61]}- #[fg=colour37]#H'


# plugins conf
set -g @continuum-restore 'off' # do not auto-restore saved sessions when tmux starts.
set -g @continuum-boot 'on'    # automatic tmux start

set -g @open 'C-o'
set -g @open-editor 'o'

set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'

# settings for sysstat
set -g @sysstat_cpu_color_low "colour076"
set -g @sysstat_cpu_color_medium "colour220"
set -g @sysstat_cpu_color_stress "colour160"
set -g @sysstat_mem_color_low "colour076"
set -g @sysstat_mem_color_medium "colour220"
set -g @sysstat_mem_color_stress "colour160"
